[default]

api_prefix = "/api/v1"
expose_port = 1912
build_date = "unknown"
rcdp_service_api_key = "changeme"

# Database
#db_user = "rda"
#db_password = "change_me_password"
#db_host = "localhost"
#db_port = 5432
#db_name = "rda"

# Provide a DB_URL so Dynaconf `app_settings.DB_URL` is available inside the container
# Override with environment variables or secrets in production as needed.
db_url = "postgresql+psycopg2://rda:my_secret_password@postgres:5432/rda"

# Email / SMTP (optional)
mail_host = "maildev"
mail_port = 1025
mail_usr = ""
mail_pass = ""
mail_from = "e.indarto@gmail.com"
mail_to = ["eko.indarto@dans.knaw.nl"]
mail_use_tls = true
mail_use_ssl = false
mail_use_auth = false

reload_enable = true



# Logging
log_level = 10
log_file = "@format {env[BASE_DIR]}/logs/rcdp.log"
log_format = '%(asctime)s %(levelname)s %(name)s %(threadName)s : %(message)s'

#data
data_institution_mapping = "@format {env[BASE_DIR]}/resources/data/mapping/institution_mapping.csv"

db_dialect="postgresql+psycopg2"

# Other
otlp_enable = false
